version: '3'

services:
  webserver:
    image: nginx:1.14.2-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./public_html:/public_html
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw